# Generated by Django 4.2.7 on 2023-11-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=13)),
                ('country', models.CharField(max_length=15)),
                ('details', models.CharField(max_length=1500)),
                ('LastDate', models.DateField()),
            ],
        ),
    ]
