# Generated by Django 4.2.7 on 2023-11-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyCondidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.CharField(max_length=20)),
                ('CandidatesEmail', models.CharField(max_length=100)),
                ('CandidatesMobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
