# Generated by Django 4.2.7 on 2023-11-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_applycondidates_alter_candidates_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplyCondidates',
            new_name='ApplyCondidate',
        ),
    ]
